import { graphql } from "graphql";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";

const graphcms = new GraphQLClient(
  "https://api-ap-south-1.graphcms.com/v2/cl4d2pwih59bq01z67b9t7ofy/master"
);

//we have use query to pull out the data from the above api

const QUERY = gql`
  {
    posts {
      id
      title
      slug
      date_published
      content {
        html
      }
      author {
        name
        avator {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}
